version: '2.1'
orbs:
  node: circleci/node@4.5.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: |
          yarn install
          yarn add firebase-tools
          yarn build
          node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
      - store_artifacts:
          path: README.md
          destination: .artifact

workflows:
  build_and_deploy:
    jobs:
      - build
